/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CompiledOperations {
  GetFiles: {
    path: '/files';
    method: 'get';
    controller: 'files.controllers';
    pathParams: {};
    queryParams: {
      path?: string;
    };
    requestBody?: unknown;
    response: {
      data: {
        root: string;
        items: ItemInfo[];
      };
    };
  };
  UploadFile: {
    path: '/files';
    method: 'post';
    controller: 'files.controllers';
    pathParams: {};
    queryParams: {
      path?: string;
    };
    requestBody?: {
      [k: string]: unknown;
    };
    response: {
      data: {};
    };
  };
}
export interface ItemInfo {
  name: string;
  path: string;
  type: 'file' | 'folder';
}
